/*
 * Generated by XDoclet - Do not edit!
 */
package lu.dtm;

/**
 * Message Driven layer for busListener.
 * @generated 
 * @wtp generated
 */
public class busListenerMdb
   extends lu.dtm.BusListener
   implements javax.ejb.MessageDrivenBean, 
              javax.jms.MessageListener 
{
   public void setMessageDrivenContext(javax.ejb.MessageDrivenContext ctx) throws javax.ejb.EJBException
   {
      super.setMessageDrivenContext(ctx);
   }

   public void ejbRemove() 
   {
      super.ejbRemove();
   }

}
